Theme, Documentation and Weblog
jonas-rem/lwm2m_server pull request #19
Opened 2024-05-15 19:17 UTC by Kappuccino111

Completes the initial setup of the documentation @jonas-rem . Please review and merge.

2024-05-15 20:51 UTC, jonas-rem requested changes
Prompt highlighting does not work anymore with this theme, but I could not figure out why. But that is not so important right now, we can look into it later.

This should usually highlight the prompt in a different color do distinguish between prompt and command.
```
.. code-block:: console

  host:lwm2m_server/server$ cmd
```

The logo looks good in the dark mode, but not really good in the light mode. Is it possible to make the background of the image transparent so that it looks good in any environment?

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/conf.py
> +    'papersize': 'letterpaper',
A4 is more common, right? I think only North America uses letter paper format.

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/conf.py
> +    "conf_py_path": "/docs/source/",
The whole html_context block is now handled in the theme options. As far as I saw we can remove this block entirely now.

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/conf.py
> -    'sphinx.ext.imgconverter'
The imageconverter package is required for converting svg images for the pdf/latex output.

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/conf.py
> -    'fontpkg': '\\usepackage{lmodern}',
I think using lmodern font makes the appearance of the generated pdf much better.

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/index.rst
> +Welcome to Flow Nexus, your comprehensive solution for small to medium scale IoT deployments. This platform is designed to streamline the setup, configuration, and use of IoT devices, making it easie
Now comes the linewidth discussion ;). I prefer 80 chars per line (80-100 in c-code, max 120 in python/java code) as this improves readability in the editor. Do you have a particular preference?

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/index.rst
> +Welcome to Flow Nexus, your comprehensive solution for small to medium scale IoT deployments. This platform is designed to streamline the setup, configuration, and use of IoT devices, making it easie
s/easier than ever/easy

For the documentation we should focus on a scientific writing style whenever possible, avoiding adjectives and phrases that represent emotion. This is the way papers are written, it represents more seriousness.

2024-05-15 20:51 UTC, jonas-rem commented on doc/source/index.rst
> +Our vision for Flow Nexus is to create a user-friendly, efficient, and robust platform for IoT management. We aim to simplify the complexities of IoT deployments, making them accessible and manageabl
should we add `Open Source`?

2024-05-15 21:02 UTC, jonas-rem commented
@Kappuccino111 the theme looks good, I like the dynamic rendering of the contents section on the right! The Weblog is also a good idea to inform about the project. A more detailed/technical info will anyways be part of releases.

2024-05-21 16:40 UTC, Kappuccino111 commented on doc/requirements.txt
> +sphinx-book-theme
- [x] Mentioned the theme versioning 
- [x] Wrote a custom css file for highlighting the prompt.
- [x] Modified the logo to be more artistic and also support transparent PNGs. Looks much better now 😁

2024-05-21 16:44 UTC, Kappuccino111 commented on doc/source/conf.py
> +    version = "0.1"
- [x] Removed trailing whitespaces 
- [x] Removed the try catch block (did not have git tags configured earlier, will need a note in the readme for the same?)

2024-05-21 16:45 UTC, Kappuccino111 commented on doc/source/conf.py
> +    'sphinxcontrib.newsfeed',
- [x] Was trying to configure multiple things, but would have been too complicated. So removed them for now 👍

2024-05-21 16:47 UTC, Kappuccino111 commented on doc/source/conf.py
> +    "announcement": "🚧 This repository is currently in active development. Some features may not be fully functional or may change significantly.🚧",
- [x] Yep, I also had that in my mind initially 😂. Removed.

2024-05-21 16:54 UTC, Kappuccino111 commented on doc/source/index.rst
> +Welcome to Flow Nexus, your comprehensive solution for small to medium scale IoT deployments. This platform is designed to streamline the setup, configuration, and use of IoT devices, making it easie
- [x] Fixed for better readability

2024-05-21 17:10 UTC, Kappuccino111 commented on doc/source/conf.py
> +    version = "0.1"
@jonas-rem there seems to be the same issue in the CI pipeline, failing the git tag check

2024-05-21 17:13 UTC, Kappuccino111 commented on doc/source/conf.py
> -    'sphinx.ext.imgconverter'
- [x] Yep, added back again.

2024-05-21 17:33 UTC, Kappuccino111 commented
@jonas-rem have updated most of the changes. Please check and merge

2024-05-21 19:17 UTC, closed without merging